import { IAttributes as IRegisterProgramMembershipActionAttributes } from '../action/interact/register/programMembership';
import { IExtendId } from '../autoGenerated';
import { IProgramMembership } from '../programMembership';
import * as TransactionFactory from '../transaction';
import TransactionType from '../transactionType';

export type IStartParamsWithoutDetail =
    TransactionFactory.IStartParams<TransactionType.RegisterProgramMembership, IAgent, undefined, IObjectWithoutDetail>;

/**
 * 取引開始パラメーターインターフェース
 */
export type IStartParams = TransactionFactory.IStartParams<TransactionType.RegisterProgramMembership, IAgent, undefined, IObject>;

export interface IAgent {
    typeOf: string;
    id?: string;
    name: string;
    url?: string;
}

/**
 * メンバーシップ通知パラメータ
 */
export interface IInformProgramMembershipParams {
    /**
     * 通知先
     */
    recipient?: {
        /**
         * 通知URL
         */
        url?: string;
    };
}

export interface IPotentialActionsParams {
    registerProgramMembership?: {
        potentialActions?: {
            informProgramMembership?: IInformProgramMembershipParams[];
        };
    };
}

/**
 * 確定パラメーターインターフェース
 */
export interface IConfirmParams {
    object?: {
        membershipNumber?: string;
    };
    /**
     * 確定後アクション
     */
    potentialActions?: IPotentialActionsParams;
}

// tslint:disable-next-line:no-empty-interface
export interface IResult {
}

/**
 * エラーインターフェース
 */
export type IError = any;

export interface IObjectWithoutDetail {
    /**
     * 会員番号
     * Chevre使用側が指定(ユニーク必須)
     */
    membershipNumber: string;
    /**
     * 対象プログラム
     */
    membershipFor: { id: string };
}

/**
 * 取引対象物インターフェース
 */
// tslint:disable-next-line:no-empty-interface
export interface IObject extends IProgramMembership {
}

export interface IPotentialActions {
    registerProgramMembership: IRegisterProgramMembershipActionAttributes[];
}

export interface IAttributes extends TransactionFactory.IAttributes<IStartParams, IResult, IError, IPotentialActions> {
}

/**
 * 取引インターフェース
 */
export type ITransaction = IExtendId<IAttributes>;

export interface ISearchConditions extends TransactionFactory.ISearchConditions<TransactionType.RegisterProgramMembership> {
    object?: any;
}
