import { IAttributes as IRegisterServiceActionAttributes } from '../action/interact/register/service';
import { IAttributes as IMoneyTransferActionAttributes } from '../action/transfer/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import OfferType from '../offerType';
import { IProduct } from '../product';
import { IInformParams } from '../project';
import * as TransactionFactory from '../transaction';
import TransactionType from '../transactionType';

export type IStartParamsWithoutDetail =
    TransactionFactory.IStartParams<TransactionType.RegisterService, IAgent, undefined, IObjectWithoutDetail>;

/**
 * 取引開始パラメーターインターフェース
 * サービス: MembershipService,PaymentCardであればserviceOutputを発行する
 */
export type IStartParams = TransactionFactory.IStartParams<TransactionType.RegisterService, IAgent, undefined, IObject>;

export interface IAgent {
    typeOf: string;
    id?: string;
    name: string;
    url?: string;
}

export interface IPotentialActionsParams {
    registerService?: {
        potentialActions?: {
            informServiceOutput?: IInformParams[];
        };
    };
}

/**
 * 確定パラメーターインターフェース
 */
export interface IConfirmParams {
    id?: string;
    transactionNumber?: string;
    endDate?: Date;
    object?: any;
    potentialActions?: IPotentialActionsParams;
}

// tslint:disable-next-line:no-empty-interface
export interface IResult {
}

/**
 * エラーインターフェース
 */
export type IError = any;

export interface IAcceptedOffer {
    typeOf: OfferType.Offer;
    id: string;
    itemOffered: IProduct;
}

export type IObjectWithoutDetail = IAcceptedOffer[];

export type IObject = IAcceptedOffer[];

export interface IPotentialActions {
    moneyTransfer: IMoneyTransferActionAttributes[];
    registerService: IRegisterServiceActionAttributes[];
}

export interface IAttributes extends TransactionFactory.IAttributes<IStartParams, IResult, IError, IPotentialActions> {
}

/**
 * 取引インターフェース
 */
export type ITransaction = IExtendId<IAttributes>;

export interface ISearchConditions extends TransactionFactory.ISearchConditions<TransactionType.RegisterService> {
    object?: any;
}
