import { IExtendId } from '../autoGenerated';
import { IClientUser } from '../clientUser';
import { IEvent as IScreeningEvent } from '../event/screeningEvent';
import * as ReservationFactory from '../reservation';
import * as EventReservationFactory from '../reservation/event';
import * as TransactionFactory from '../transaction';
import TransactionType from '../transactionType';

export type IStartParamsWithoutDetail = TransactionFactory.IStartParams<TransactionType.Reserve, IAgent, undefined, IObjectWithoutDetail>;
/**
 * 取引開始パラメーターインターフェース
 */
export type IStartParams = TransactionFactory.IStartParams<TransactionType.Reserve, IAgent, undefined, IObject>;
export interface IAgent {
    typeOf: string;
    id?: string;
    name: string;
    url?: string;
}
export interface IResult {
    /**
     * 取引結果としてのイベント予約
     */
    reservations: EventReservationFactory.IReservation<IScreeningEvent>[];
}
/**
 * エラーインターフェース
 */
export type IError = any;
export interface IObjectWithoutDetail {
    clientUser?: IClientUser;
    event: { id: string };
    tickets: ReservationFactory.IAcceptedTicket[];
    notes: string;
}
/**
 * 取引対象物インターフェース
 */
export interface IObject extends IObjectWithoutDetail {
    event: IScreeningEvent;
    tickets: ReservationFactory.ITicket[];
}
export interface IPotentialActions {
    reserve: any;
}
export type ITransaction = IExtendId<IAttributes>;
/**
 * 取引属性インターフェース
 */
export interface IAttributes
    extends TransactionFactory.IAttributes<IStartParams, IResult, IError, IPotentialActions> {
}
