import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export type IData = any;

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.AggregateOnProject;
    data: IData;
}

/**
 * プロジェクト上での集計タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
