/**
 * 予約キャンセルタスクファクトリー
 */
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';
import TransactionType from '../transactionType';

export interface IData {
    transaction: {
        typeOf: TransactionType;
        id: string;
    };
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelReservation;
    data: IData;
}
export type ITask = IExtendId<IAttributes>;
