import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';
import { ITransaction } from '../transaction/placeOrder';

export interface IData {
    object: ITransaction;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.DeleteTransaction;
    data: IData;
}
/**
 * 取引削除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
