import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';
import { ITransaction as IMoneyTransfer } from '../transaction/moneyTransfer';
import { ITransaction as IPlaceOrder } from '../transaction/placeOrder';
import { ITransaction as IReturnOrder } from '../transaction/returnOrder';

export type IObject = IPlaceOrder | IReturnOrder | IMoneyTransfer;
export interface IData {
    object: IObject;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.DeleteTransaction;
    data: IData;
}
/**
 * 取引削除タスク
 */
export type ITask = IExtendId<IAttributes>;
