import { IAuthorization } from '../authorization';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    object: IAuthorization;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.DeleteAuthorization;
    data: IData;
}
/**
 * 承認削除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
