import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import TaskName from '../taskName';

export interface IData {
    theaterCode: string;
}

export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.AggregateScreeningEvent;
    data: IData;
}

/**
 * COA券種インポートタスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
