import { IPotentialActions as IOrderActionPotentialActions } from '../action/trade/order';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    object: { confirmationNumber: string; orderNumber: string };
    potentialActions?: IOrderActionPotentialActions;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PlaceOrder;
    data: IData;
}
/**
 * 注文タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
