import { IAttributes as IReturnActionAttributes } from '../action/transfer/return/paymentMethod';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = IReturnActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmRefund;
    data: IData;
}
/**
 * 決済資産取引返却タスク
 */
export type ITask = IExtendId<IAttributes>;
