import { IAttributes as IReturnMoneyTransferActionAttributes } from '../action/transfer/return/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = IReturnMoneyTransferActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnMoneyTransfer;
    data: IData;
}
/**
 * 入金返却タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
