import * as SendOrderActionFactory from '../action/transfer/send/order';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    project: IProject;
    object: SendOrderActionFactory.IObject;
    potentialActions?: SendOrderActionFactory.IPotentialActions;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SendOrder;
    data: IData;
}
/**
 * 注文配送タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
