import { IOffer } from './offer';
import { IProgramMembership } from './programMembership';
import { IProject } from './project';
import { IThing } from './thing';

export interface IHasOfferCatalog {
    typeOf: 'OfferCatalog';
    id?: string;
}

export type IServiceOutput = IProgramMembership | IThing;

/**
 * サービスインターフェース
 * @see https://schema.org/Service
 */
export interface IService extends IThing {
    project: IProject;
    typeOf: string;
    id?: string;
    /**
     * Indicates an OfferCatalog listing for this Organization, Person, or Service.
     */
    hasOfferCatalog?: IHasOfferCatalog;
    /**
     * An offer to provide this item
     */
    offers?: IOffer[];
    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     */
    serviceOutput?: IServiceOutput | IServiceOutput[];
    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     */
    serviceType?: any;
}
