import { IMonetaryAmount } from './monetaryAmount';
import { IOffer } from './offer';
import { IPermit } from './permit';
// import { IProgramMembership } from './programMembership';
import { IProject } from './project';
import { IThing } from './thing';

export interface IHasOfferCatalog {
    typeOf: 'OfferCatalog';
    id?: string;
}

// export type IServiceOutput = IProgramMembership | IPermit;
export type IServiceOutput = IPermit;

/**
 * ポイント特典インターフェース
 */
export interface IPointAward {
    typeOf: 'MoneyTransfer';
    amount?: IMonetaryAmount;
    toLocation?: any;
}

/**
 * サービスインターフェース
 * @see https://schema.org/Service
 */
export interface IService extends IThing {
    project: IProject;
    typeOf: string;
    id?: string;
    /**
     * Indicates an OfferCatalog listing for this Organization, Person, or Service.
     */
    hasOfferCatalog?: IHasOfferCatalog;
    /**
     * An offer to provide this item
     */
    offers?: IOffer[];
    pointAward?: IPointAward;
    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     */
    serviceOutput?: IServiceOutput;
    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     */
    serviceType?: any;
}
