import * as waiter from '@waiter/factory';

import { IExtendId } from './autoGenerated';
import * as EmailFactory from './creativeWork/message/email';
import { IWebApplicationAttributes } from './creativeWork/softwareApplication/webApplication';
import { IMultilingualString } from './multilingualString';
import { OrganizationType } from './organizationType';
import { IIdentifier, IPersonAttributes } from './person';
import { PersonType } from './personType';
import { SortType } from './sortType';
import { TransactionStatusType } from './transactionStatusType';
import { TransactionTasksExportationStatus } from './transactionTasksExportationStatus';
import { TransactionType } from './transactionType';

export interface IAgentAsWebApplication extends IWebApplicationAttributes {
    name?: string;
}
export interface IAgentAsPerson extends IPersonAttributes {
    name?: string;
}
// 最適化(2022-05-30~)
export type IAgent = IAgentAsWebApplication | IAgentAsPerson;
// 最適化(2022-05-30~)
// export type ISeller = Omit<SellerFactory.ISeller,
//     'branchCode' | 'paymentAccepted' | 'additionalProperty'
//     | 'hasMerchantReturnPolicy' | 'email' | 'telephone' | 'location' | 'url' | 'project'>;
/**
 * 販売者
 */
export interface ISeller {
    typeOf: OrganizationType.Corporation;
    id: string;
    name: IMultilingualString;
}
/**
 * Eメール送信パラメータ
 */
export interface ISendEmailMessageParams {
    /**
     * Eメールカスタマイズ
     * メール本文をカスタマイズしたい場合、PUGテンプレートを指定
     * 挿入変数として`order`を使用できます
     * {@link https://pugjs.org/api/getting-started.html}
     */
    object?: EmailFactory.ICustomization;
}
export interface IPassportBeforeStart {
    /**
     * WAITER許可証発行者
     */
    issuer: string;
    /**
     * WAITER許可証トークン
     */
    token: waiter.passport.IEncodedPassport;
    /**
     * WAITER許可証トークンシークレット
     */
    secret: string;
}
export interface IProject {
    id: string;
    typeOf: OrganizationType.Project;
}
/**
 * 取引開始パラメータ
 */
export interface IStartParams<T extends TransactionType, TAgent, TRecipient, TObject> {
    project: IProject;
    /**
     * 取引タイプ
     */
    typeOf: T;
    /**
     * 取引主体
     */
    agent: TAgent;
    /**
     * 取引物受取者
     */
    recipient?: TRecipient;
    /**
     * 取引対象
     */
    object: TObject;
    /**
     * 取引進行期限
     */
    expires: Date;
}
export type IAttributes<TStartParams, TResult, TError, TPotentialActions> = TStartParams & {
    /**
     * 取引状態
     */
    status: TransactionStatusType;
    /**
     * 取引結果
     */
    result?: TResult;
    /**
     * 取引エラー
     */
    error?: TError;
    /**
     * 取引進行期限
     */
    expires: Date;
    /**
     * 取引開始日時
     */
    startDate: Date;
    /**
     * 取引終了日時
     */
    endDate?: Date;
    /**
     * タスクエクスポート日時
     */
    tasksExportedAt?: Date;
    /**
     * タスクエクスポート状態
     */
    tasksExportationStatus: TransactionTasksExportationStatus;
    /**
     * 事後に発生するアクション
     */
    potentialActions?: TPotentialActions;
};
export type ITransaction<TStartParams, TResult, TError, TPotentialActions> =
    IExtendId<IAttributes<TStartParams, TResult, TError, TPotentialActions>>;
/**
 * ソート条件
 */
export interface ISortOrder {
    startDate?: SortType;
}
export interface ISearchConditions<T extends TransactionType> {
    limit?: number;
    page?: number;
    sort?: ISortOrder;
    project?: {
        id?: { $eq?: string };
    };
    /**
     * 取引タイプ
     */
    typeOf: T;
    /**
     * IDリスト
     */
    ids?: string[];
    /**
     * ステータスリスト
     */
    statuses?: TransactionStatusType[];
    /**
     * 開始日時(から)
     */
    startFrom?: Date;
    /**
     * 開始日時(まで)
     */
    startThrough?: Date;
    /**
     * 終了日時(から)
     */
    endFrom?: Date;
    /**
     * 終了日時(まで)
     */
    endThrough?: Date;
    agent?: {
        typeOf?: PersonType;
        ids?: string[];
        identifiers?: IIdentifier;
        givenName?: string;
        familyName?: string;
        telephone?: string;
        email?: string;
    };
    tasksExportationStatuses?: TransactionTasksExportationStatus[];
}
