import { IAttributes as IAcceptCOAOfferActionAttributes } from '../action/accept/coaOffer';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = Pick<IAcceptCOAOfferActionAttributes, 'agent' | 'object' | 'potentialActions' | 'purpose' | 'typeOf'>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.AcceptCOAOffer;
    data: IData;
}
/**
 * COA興行オファー採用タスク
 */
export type ITask = IExtendId<IAttributes>;
