import { IExtendId } from '../autoGenerated';
import { EventType } from '../eventType';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    typeOf: EventType.ScreeningEvent;
    id: string;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.AggregateOffers;
    data: IData;
}
/**
 * オファー集計タスク
 */
export type ITask = IExtendId<IAttributes>;
