import { IPurpose } from '../action/cancel/reservation';
import { AssetTransactionType } from '../assetTransactionType';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

// optimize(2024-07-01~)
// export interface IData {
//     actionAttributes: ICancelReservationActionAttributes[];
// }
export interface ICancelPurpose extends IPurpose {
    typeOf: AssetTransactionType.Reserve;
}
export interface IData { purpose: ICancelPurpose; }
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelPendingReservation;
    data: IData;
}
/**
 * 保留予約取消タスク
 */
export type ITask = IExtendId<IAttributes>;
