import { IAttributes as ICancelReservationActionAttributes } from '../action/cancel/reservation';
import { AssetTransactionType } from '../assetTransactionType';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IPotentialCancelAction extends ICancelReservationActionAttributes {
    purpose: { id: string; typeOf: AssetTransactionType.CancelReservation };
}
export interface IData {
    actionAttributes: IPotentialCancelAction[];
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CancelReservation;
    data: IData;
}
/**
 * 予約取消タスク
 */
export type ITask = IExtendId<IAttributes>;
