import { IAttributes as ICheckMovieTicketActionAttributes, IPurpose } from '../action/check/paymentMethod/movieTicket';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData extends Pick<ICheckMovieTicketActionAttributes, 'agent' | 'object' | 'project' | 'purpose' | 'typeOf'> {
    purpose: IPurpose;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CheckMovieTicket;
    data: IData;
}
/**
 * 決済カード認証タスク
 */
export type ITask = IExtendId<IAttributes>;
