import { IAttributes as ICheckActionAttributes } from '../action/check';
import { IExtendId } from '../autoGenerated';
import { OrderType } from '../order';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IResourceAsOrder {
    orderNumber: string;
    typeOf: OrderType.Order;
}
export type IResource = IResourceAsOrder;
export type IData = Pick<ICheckActionAttributes<IResource, any>, | 'object' | 'project' | 'typeOf'>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.CheckResource;
    data: IData;
}
/**
 * リソース検証タスク
 */
export type ITask = IExtendId<IAttributes>;
