import { IAttributes as IConfirmRegisterServiceActionAttributes } from '../action/interact/confirm/registerService';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = IConfirmRegisterServiceActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmRegisterService;
    data: IData;
}
/**
 * サービス登録確定タスク
 */
export type ITask = IExtendId<IAttributes>;
