import { IAttributes as IConfirmMoneyTransferActionAttributes } from '../action/interact/confirm/moneyTransfer';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = IConfirmMoneyTransferActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ConfirmMoneyTransfer;
    data: IData;
}
/**
 * 通貨転送確定タスク
 */
export type ITask = IExtendId<IAttributes>;
