import { IExtendId } from '../autoGenerated';
import { IOrder } from '../order';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    object: IOrder;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.DeleteOrder;
    data: IData;
}
/**
 * 注文削除タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
