import { IAttributes as IGivePointAwardActionAttributes } from '../action/transfer/give/pointAward';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = IGivePointAwardActionAttributes;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.GivePointAward;
    data: IData;
}
/**
 * ポイント特典付与タスク
 */
export type ITask = IExtendId<IAttributes>;
