import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    /**
     * 施設コード
     */
    locationBranchCode: string;
    /**
     * 仕入れ期間from
     */
    importFrom: Date;
    /**
     * 仕入れ期間through
     */
    importThrough: Date;
    /**
     * 施設を保管するかどうか
     */
    saveMovieTheater: boolean;
    /**
     * 施設コンテンツを保管するかどうか
     */
    saveScreeningEventSeries: boolean;
    saveScreeningEventSeriesPeriodInMonth: number;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ImportEventsFromCOA;
    data: IData;
}
/**
 * イベントインポートタスク
 */
export type ITask = IExtendId<IAttributes>;
