import { AssetTransactionType } from '../assetTransactionType';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';
import { TransactionStatusType } from '../transactionStatusType';

export interface IPurposeAsOrder {
    typeOf: 'Order';
    confirmationNumber: string;
    orderNumber: string;
}
export interface IObjectAsPayTransaction {
    typeOf: AssetTransactionType.Pay;
    transactionNumber: string;
    status: TransactionStatusType.Confirmed;
    // 確定時の決済方法区分指定(2023-08-29~)
    object?: {
        paymentMethod?: { identifier?: string };
    };
}
export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    object: IObjectAsPayTransaction;
    purpose: IPurposeAsOrder;
    useOnOrderStatusChanged: boolean;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnAssetTransactionStatusChanged;
    data: IData;
}
/**
 * 資産取引ステータス変更時タスク
 */
export type ITask = IExtendId<IAttributes>;
