import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    /**
     * 承認コード
     */
    code: string;
    project: { id: string };
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnAuthorizationCreated;
    data: IData;
}
/**
 * 承認作成時タスク
 */
export type ITask = IExtendId<IAttributes>;
