import { IExtendId } from '../autoGenerated';
import { EventType } from '../eventType';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IChangedEvent {
    id: string;
    typeOf: EventType;
    project: { id: string };
}
export interface IData {
    event: IChangedEvent[];
    id: string[];
    project: { id: string };
    typeOf: EventType;
    isNew: boolean;
    useInform: boolean;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnEventChanged;
    data: IData;
}
/**
 * イベント変更時タスク
 */
export type ITask = IExtendId<IAttributes>;
