import { IExtendId } from '../autoGenerated';
import { EventType } from '../eventType';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    id: string[];
    project: { id: string };
    typeOf: EventType;
    isNew: boolean;
    useInform: boolean;
    /**
     * 関連リソースへの同期有無(2023-07-28~)
     */
    useSync?: boolean;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnEventChanged;
    data: IData;
}
/**
 * イベント変更時タスク
 */
export type ITask = IExtendId<IAttributes>;
