import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IObjectAsOrder {
    confirmationNumber: string;
    orderNumber: string;
}
export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    object: IObjectAsOrder;
    useOnOrderStatusChanged: boolean;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnOrderPaymentCompleted;
    data: IData;
}
/**
 * 注文に対する決済完了時タスク
 */
export type ITask = IExtendId<IAttributes>;
