import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    object: { confirmationNumber: string; orderNumber: string };
    useOnOrderStatusChanged: boolean;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnOrderPaymentCompleted;
    data: IData;
}
/**
 * 注文に対する全決済完了時タスク
 */
export type ITask = IExtendId<IAttributes>;
