import { IAccountTitle } from '../accountTitle';
import { IExtendId } from '../autoGenerated';
import { ICategoryCode } from '../categoryCode';
import { CreativeWorkType } from '../creativeWorkType';
import { OrganizationType } from '../organizationType';
import { PlaceType } from '../placeType';
import { ProductType } from '../product';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type AccountTitleType = IAccountTitle['typeOf'];
export type CategoryCodeType = ICategoryCode['typeOf'];
export type IResourceTypeOf = AccountTitleType | CategoryCodeType | CreativeWorkType
    | OrganizationType.Corporation | PlaceType.MovieTheater | ProductType;
export interface IData {
    id: string[];
    project: { id: string };
    typeOf: IResourceTypeOf;
    isNew: boolean;
    // 削除に対応(2023-07-28~)
    isDeleted?: boolean;
    useInform: boolean;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.OnResourceUpdated;
    data: IData;
}
/**
 * リソース変更時タスク
 */
export type ITask = IExtendId<IAttributes>;
