import { IAttributes as IPayActionAttributes } from '../action/trade/pay';
import { IOptimizedPayAction4order } from '../assetTransaction/pay';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export { IOptimizedPayAction4order };
export type IPayActionData = Pick<
    IPayActionAttributes,
    'agent' | 'instrument' | 'location' | 'object' | 'potentialActions' | 'project' | 'purpose' | 'recipient' | 'typeOf'
>;
export type IData = IPayActionData | IOptimizedPayAction4order;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.Pay;
    data: IData;
}
/**
 * 決済タスク
 */
export type ITask = IExtendId<IAttributes>;
