import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    object: { confirmationNumber: string; orderNumber: string };
    // potentialActions?: IOrderActionPotentialActions; // 廃止(2023-08-21~)
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PlaceOrder;
    data: IData;
}
/**
 * 注文タスク
 */
export type ITask = IExtendId<IAttributes>;
