import { IObjectWithoutDetail, IPurpose } from '../action/authorize/paymentMethod/any';
import { ILocation } from '../action/trade/pay';
import { IExtendId } from '../autoGenerated';
import { PaymentServiceType } from '../service/paymentService';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    project: { id: string };
    agent: { id: string };
    object: Pick<IObjectWithoutDetail, 'amount' | 'creditCard' | 'issuedThrough' | 'method' | 'paymentMethod'>;
    purpose: IPurpose;
    paymentServiceType: PaymentServiceType;
    location: ILocation;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.PublishPaymentUrl;
    data: IData;
}
/**
 * 決済URL発行タスク
 */
export type ITask = IExtendId<IAttributes>;
