import { IPotentialReturnInvoiceAction } from '../action/transfer/return/order';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IData = IPotentialReturnInvoiceAction;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnPayTransaction;
    data: IData;
}
/**
 * 決済資産取引返却タスク
 */
export type ITask = IExtendId<IAttributes>;
