import { IAttributes as IReturnOrderActionAttributes } from '../action/transfer/return/order';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

// potentialActionsを廃止(2023-08-22~)
export type IData = Pick<IReturnOrderActionAttributes, 'agent' | 'object' | 'project' | 'typeOf'>;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.ReturnOrder;
    data: IData;
}
/**
 * 注文返品タスク
 */
export type ITask = IExtendId<IAttributes>;
