import { IAttributes as ISendEmailMessageActionAttributest } from '../action/transfer/send/message/email';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IActionAttributes = Pick<
    ISendEmailMessageActionAttributest,
    'agent' | 'object' | 'project' | 'purpose' | 'recipient' | 'typeOf'
>;
export interface IData {
    /**
     * Eメール送信アクション属性
     */
    actionAttributes: IActionAttributes;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SendEmailMessage;
    data: IData;
}
/**
 * Eメール送信タスク
 */
export type ITask = IExtendId<IAttributes>;
