import * as SendOrderActionFactory from '../action/transfer/send/order';
import { IExtendId } from '../autoGenerated';
import { IProject } from '../project';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IObject = SendOrderActionFactory.IObject & {
    confirmationNumber: string;
};
export interface IData {
    project: Pick<IProject, 'id' | 'typeOf'>;
    object: IObject;
    // potentialActions?: SendOrderActionFactory.IPotentialActions; // 廃止(2023-08-21~)
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SendOrder;
    data: IData;
}
/**
 * 注文配送タスク
 */
export type ITask = IExtendId<IAttributes>;
