import { IExtendId } from '../autoGenerated';
import { PlaceType } from '../placeType';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    /**
     * 施設ID
     */
    id: string;
    project: { id: string };
    typeOf: PlaceType.MovieTheater;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SyncScreeningRooms;
    data: IData;
}
/**
 * ルーム同期タスク
 */
export type ITask = IExtendId<IAttributes>;
