import { IExtendId } from '../autoGenerated';
import { OfferType } from '../offerType';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    id?: { $in: string[] };
    identifier?: { $in: string[] };
    project: { id: string };
    typeOf: OfferType.Offer;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.SyncAggregateOffer;
    data: IData;
}
/**
 * オファー同期タスク
 */
export type ITask = IExtendId<IAttributes>;
