import { IAttributes as IInformActionAttributes, IObject } from '../action/interact/inform';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IPotentialInformAction = Pick<IInformActionAttributes<IObject>, 'object' | 'purpose' | 'recipient'>; // optimize(2024-07-01~)
export type IData = IPotentialInformAction;
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.TriggerWebhook;
    data: IData;
}
/**
 * 通知タスク
 */
export type ITask = IExtendId<IAttributes>;
