import { IAttributes as IUseReservationActionAttributes, IReservationAsObject } from '../action/consume/use/reservation';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IUseReservationObject = Pick<IReservationAsObject, 'id' | 'typeOf'>;
export type IData = Pick<
    IUseReservationActionAttributes,
    'agent' | 'instrument' | 'location' | 'project' | 'typeOf'> & {
        object: IUseReservationObject;
        /**
         * 発券前に予約アクションを実行するかどうか
         */
        reserveIfNotYet: boolean;
    };
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.UseReservation;
    data: IData;
}
/**
 * 予約使用タスク
 */
export type ITask = IExtendId<IAttributes>;
