import { ITransaction as IPayTransaction } from '../assetTransaction/pay';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export interface IData {
    object: IPayTransaction;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.VoidPayment;
    data: IData;
}
/**
 * 決済中止タスクインターフェース
 */
export type ITask = IExtendId<IAttributes>;
