import { ITransaction as IPayTransaction } from '../assetTransaction/pay';
import { IExtendId } from '../autoGenerated';
import * as TaskFactory from '../task';
import { TaskName } from '../taskName';

export type IPayTransactionAsObject = Pick<IPayTransaction, 'project' | 'typeOf' | 'id' | 'transactionNumber' | 'recipient' | 'object'>;
export interface IData {
    object: IPayTransactionAsObject;
}
export interface IAttributes extends TaskFactory.IAttributes {
    name: TaskName.VoidPayment;
    data: IData;
}
/**
 * 決済中止タスク
 */
export type ITask = IExtendId<IAttributes>;
