import { IAttributes as IMoneyTransferActionAttributes, ILocation, IPendingTransaction, IRecipient as IMoneyTransferRecipient } from '../action/transfer/moneyTransfer';
import * as TransactionFactory from '../assetTransaction';
import AssetTransactionType from '../assetTransactionType';
import { IExtendId } from '../autoGenerated';
import { IMonetaryAmount } from '../monetaryAmount';

export type IAgent = any;

export type IRecipient = IMoneyTransferRecipient;

export type IFromLocation = ILocation;

export type IToLocation = ILocation;

/**
 * 取引対象物インターフェース
 */
export interface IObject {
    /**
     * 金額
     */
    amount: IMonetaryAmount;
    /**
     * 転送元
     */
    fromLocation: IFromLocation;
    /**
     * 転送先
     */
    toLocation: IToLocation;
    /**
     * 取引説明
     */
    description?: string;
    pendingTransaction?: IPendingTransaction;
}

export type IObjectWithoutDetail = IObject;

export interface IStartParamsWithoutDetail
    extends TransactionFactory.IStartParams<AssetTransactionType.MoneyTransfer, IAgent, IRecipient, IObjectWithoutDetail> {
    recipient: IRecipient;
}

export interface IStartParams extends TransactionFactory.IStartParams<AssetTransactionType.MoneyTransfer, IAgent, IRecipient, IObject> {
    recipient: IRecipient;
}

export type IResult = any;

export type IError = any;

export interface IPotentialActions {
    /**
     * 通貨転送アクション
     */
    moneyTransfer: IMoneyTransferActionAttributes[];
}

export type ITransaction = IExtendId<IAttributes>;

/**
 * 転送取引インターフェース
 */
export interface IAttributes extends TransactionFactory.IAttributes<IStartParams, IResult, IError, IPotentialActions> {
}

export interface ISearchConditions extends TransactionFactory.ISearchConditions<AssetTransactionType.MoneyTransfer> {
    object?: {
        fromLocation?: {
            identifier?: {
                $eq?: string;
            };
        };
        toLocation?: {
            identifier?: {
                $eq?: string;
            };
        };
        pendingTransaction?: {
            identifier?: {
                $eq?: string;
            };
        };
    };
}
