import { IAttributes as ICancelReservationActionAttributes } from '../action/cancel/reservation';
import * as AssetTransactionFactory from '../assetTransaction';
import { ITransaction as IReserveTransaction } from '../assetTransaction/reserve';
import { AssetTransactionType } from '../assetTransactionType';
import { IExtendId } from '../autoGenerated';
import { IClientUser } from '../clientUser';
import { IReservation as IBusReservation, IReservationFor as IBusReservationFor } from '../reservation/busReservation';
import { IReservation as IEventReservation, IReservationFor as IEventReservationFor } from '../reservation/event';

// 最適化(2022-05-27~)
export import IAgent = AssetTransactionFactory.IAgent;
export type IStartParamsWithoutDetail =
    AssetTransactionFactory.IStartParams<AssetTransactionType.CancelReservation, IAgent, undefined, IObjectWithoutDetail>;
/**
 * 取引開始パラメータ
 */
export type IStartParams = AssetTransactionFactory.IStartParams<AssetTransactionType.CancelReservation, IAgent, undefined, IObject>;
// tslint:disable-next-line:no-empty-interface
export interface IResult {
}
/**
 * エラー
 */
export type IError = any;
export interface IObjectWithoutDetail {
    clientUser?: IClientUser;
    reservation?: {
        /**
         * 予約IDをキーに取消
         */
        id?: string;
        // id?: string | string[];
        /**
         * 予約番号をキーに取消
         */
        reservationNumber?: string;
    };
}
export type IReserveTransactionAsObject = Pick<IReserveTransaction, 'typeOf' | 'id' | 'transactionNumber'> & {
    object: {
        reservationFor: Pick<IEventReservationFor | IBusReservationFor, 'id' | 'typeOf'>;
    };
};
export type IBusReservationAsObject = Pick<
    IBusReservation,
    'id' | 'issuedThrough' | 'reservationNumber' | 'typeOf'
> & {
    reservationFor: Pick<IBusReservationFor, 'id' | 'typeOf'>;
};
export type IEventReservationAsObject = Pick<
    IEventReservation,
    'id' | 'issuedThrough' | 'reservationNumber' | 'typeOf'
> & {
    reservationFor: Pick<IEventReservationFor, 'id' | 'typeOf'>;
};
/**
 * 取引対象物
 */
export interface IObject {
    clientUser?: IClientUser;
    // 最適化(2022-12-28~)
    // transaction?: IReserveTransaction;
    transaction?: IReserveTransactionAsObject;
    reservations?: IBusReservationAsObject[] | IEventReservationAsObject[];
}
/**
 * 取引確定パラメータ
 */
export interface IConfirmParams {
    id: string;
}
export interface IPotentialActions {
    cancelReservation: ICancelReservationActionAttributes[];
}
export type ITransaction = IExtendId<IAttributes>;
/**
 * 取引属性
 */
export interface IAttributes
    extends AssetTransactionFactory.IAttributes<IStartParams, IResult, IError, IPotentialActions> {
}
export interface ISearchConditions extends AssetTransactionFactory.ISearchConditions<AssetTransactionType.CancelReservation> {
}
