import { ICategoryCode } from './categoryCode';
import { IMultilingualString } from './multilingualString';
import { IName as IOfferName, IOffer as IBaseOffer } from './offer';
import { OfferType } from './offerType';
import { IPermit } from './permit';
import { IPriceSpecification as ICategoryCodeChargeSpecification } from './priceSpecification/categoryCodeChargeSpecification';
import { IPriceSpecification as ICompoundPriceSpecification } from './priceSpecification/compoundPriceSpecification';
import { IPriceSpecification as IMovieTicketTypeChargeSpecification } from './priceSpecification/movieTicketTypeChargeSpecification';
import { IPriceSpecification as IUnitPriceSpecification } from './priceSpecification/unitPriceSpecification';
import { IProject } from './project';
import { IPropertyValue } from './propertyValue';
import { IQuantitativeValue } from './quantitativeValue';
import { SortType } from './sortType';
import { IThing } from './thing';
import { UnitCode } from './unitCode';
import * as UnitPriceOfferFactory from './unitPriceOffer';

/**
 * プロダクトタイプ
 */
export enum ProductType {
    /**
     * 興行
     */
    EventService = 'EventService',
    /**
     * メンバーシップサービス
     */
    MembershipService = 'MembershipService',
    /**
     * ペイメントカード
     */
    PaymentCard = 'PaymentCard',
    /**
     * アドオン
     */
    Product = 'Product',
    /**
     * 旅客サービス
     */
    Transportation = 'Transportation'
}

export interface IHasOfferCatalog {
    typeOf: 'OfferCatalog';
    id: string;
}
export type IMembershipPointsEarned = Pick<IQuantitativeValue<string>, 'name' | 'typeOf' | 'unitText' | 'value'>;
export type IServiceOutput = Pick<IPermit, 'typeOf' | 'amount'> & {
    membershipPointsEarned?: IMembershipPointsEarned;
    automaticRenewal?: boolean;
};
/**
 * 外部サービス認証情報
 */
export interface ICredentials {
    siteId?: string;
    sitePass?: string;
    authorizeServerDomain?: string;
    clientId?: string;
    clientSecret?: string;
}

export interface IAvailableChannel {
    typeOf: 'ServiceChannel';
    serviceUrl?: string;
    credentials?: ICredentials;
}
export type IServiceType = Pick<ICategoryCode, 'codeValue' | 'inCodeSet' | 'typeOf'>;
export type IOffer = Pick<
    IBaseOffer,
    'typeOf' | 'priceCurrency' | 'availabilityEnds' | 'availabilityStarts' | 'validFrom' | 'validThrough'
> & {
    seller?: { id?: string };
};
/**
 * プロダクト
 * {@link https://schema.org/Product}
 */
export interface IProduct extends Pick<IThing, 'name' | 'description'> {
    project: Pick<IProject, 'id' | 'typeOf'>;
    typeOf: ProductType;
    id?: string;
    availableChannel?: IAvailableChannel;
    description?: IMultilingualString;
    /**
     * Indicates an OfferCatalog listing for this Organization, Person, or Service.
     */
    hasOfferCatalog?: IHasOfferCatalog;
    name?: IMultilingualString;
    /**
     * An offer to provide this item
     */
    offers?: IOffer[];
    /**
     * The product identifier, such as ISBN. For example: meta itemprop="productID" content="isbn:123-456-789".
     */
    productID: string;
    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     */
    serviceOutput?: IServiceOutput;
    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     */
    serviceType?: IServiceType;
    additionalProperty?: IPropertyValue<string>[];
}
export type ICreateParams = Pick<
    IProduct,
    'typeOf' | 'productID' | 'name' | 'description' | 'availableChannel' | 'serviceOutput'
> & {
    hasOfferCatalog?: {
        /**
         * IDを指定する場合
         */
        id?: string;
        /**
         * カタログコードを指定する場合
         */
        identifier: string;
    };
    /**
     * サービスタイプ
     * 興行->興行区分
     * メンバーシップ->メンバーシップ区分
     * ペイメントカード->決済方法区分
     */
    serviceType?: Pick<IServiceType, 'codeValue'>;
};

export interface ISortOrder {
    productID?: SortType;
}

export interface ISearchConditions {
    limit?: number;
    page?: number;
    sort?: ISortOrder;
    project?: { id?: { $eq?: string } };
    hasOfferCatalog?: {
        id?: {
            $eq?: string;
        };
    };
    id?: {
        $eq?: string;
        $in?: string[];
    };
    name?: {
        $regex?: string;
    };
    productID?: {
        $eq?: string;
        $in?: string[];
        $regex?: string;
    };
    provider?: {
        id?: {
            /**
             * プロバイダーに指定IDの販売者が含まれる
             */
            $eq?: string;
        };
    };
    typeOf?: {
        $eq?: string;
        $in?: string[];
    };
    offers?: {
        $elemMatch?: {
            availabilityEnds?: {
                $gte?: Date;
                $lte?: Date;
            };
            availabilityStarts?: {
                $gte?: Date;
                $lte?: Date;
            };
            validFrom?: {
                $gte?: Date;
                $lte?: Date;
            };
            validThrough?: {
                $gte?: Date;
                $lte?: Date;
            };
            'seller.id'?: {
                $in?: string[];
            };
        };
    };
    serviceOutput?: {
        typeOf?: { $eq?: string };
        amount?: {
            currency?: { $eq?: string };
        };
    };
    serviceType?: {
        codeValue?: { $eq?: string };
    };
}

/**
 * サービスアウトプット検索条件
 */
export interface IServiceOutputSearchConditions {
    limit?: number;
    page?: number;
    // sort?: ISortOrder;
    project?: { id?: { $eq?: string } };
    accessCode?: { $eq?: string };
    id?: { $eq?: string };
    identifier?: {
        $eq?: string;
        $in?: string[];
    };
    issuedBy?: {
        id?: { $eq?: string };
    };
    issuedThrough?: {
        id?: { $eq?: string };
        serviceType?: {
            codeValue?: { $eq?: string };
        };
        typeOf?: { $eq?: ProductType };
    };
    typeOf?: { $eq?: string };
}

export type ICategoryCodeChargePriceComponent = Omit<ICategoryCodeChargeSpecification, 'project'>;
export type IMovieTicketTypeChargePriceComponent = Omit<IMovieTicketTypeChargeSpecification, 'project'>;
export type ITicketUnitPriceComponent = Omit<IUnitPriceSpecification, 'project'>;
export type ITicketPriceComponent = ICategoryCodeChargePriceComponent | IMovieTicketTypeChargePriceComponent | ITicketUnitPriceComponent;
export type IEligibleQuantity = Pick<IQuantitativeValue<UnitCode.C62>, 'maxValue' | 'typeOf' | 'unitCode' | 'value'>;
/**
 * プロダクトオファーの価格仕様
 */
export type ITicketPriceSpecification = Omit<ICompoundPriceSpecification<ITicketPriceComponent>, 'project'>;
export import IMinimizedTicketAddOn = UnitPriceOfferFactory.IAddOn4unitPriceOffer;
/**
 * プロダクトオファー
 */
export interface ITicketOffer extends Pick<
    IBaseOffer,
    'acceptedPaymentMethod' | // add(2023-11-15~)
    'name' | 'description' | 'alternateName' | 'color' | 'typeOf' | 'id' |
    'availability' |
    // 'availableAtOrFrom' | // discontinue(2023-12-01~)
    'category' |
    'eligibleMembershipType' | 'eligibleSeatingType' | 'eligibleMonetaryAmount' | 'eligibleSubReservation' |
    'eligibleQuantity' |
    'offeredThrough' |
    'priceCurrency' |
    'validFrom' | 'validThrough' |
    'validRateLimit' |
    'additionalProperty'
> {
    addOn?: IMinimizedTicketAddOn[];
    identifier: string;
    name: IOfferName;
    priceSpecification: ITicketPriceSpecification;
    itemOffered?: UnitPriceOfferFactory.IItemOffered;
    offerIndex?: number;
    /**
     * カタログ内ソートインデックス
     */
    sortIndex?: number;
    typeOf: OfferType.Offer;
}
